### Obtiene listado de Joyas en formato "HATEOAS".
GET http://localhost:3000/joyas?limits=3&page=2&order_by=stock_ASC

### Obtiene una joya por ID
GET http://localhost:3000/joyas/joya/1

### Obtiene joyas según filtros
GET http://localhost:3000/joyas/filtros?precio_min=25000&precio_max=30000&categoria=aros&metal=plata